apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jwtfed-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jwtfed-client
    spec:
      containers:
      - name: master
        image: andreassolberg/jwtfed-client:latest  # or just image: redishello:1.0
        env:
        - name: CLIENT_ID
          value: "https://jwt-client.andreas.labs.uninett.no/yay"
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jwtfed-client
  labels:
    app: jwtfed-client
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: jwtfed-client
